global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@smava.de'

route:
  receiver: 'OPS_Team'
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'OPS_Team'
  email_configs:
  - to: 'ashutosh.singh@smava.de'
