#!/usr/bin/env bash
APPLICATIONS='COMMONSEXTERNALLOANMERGER
BROKERAGEGINITRAINING
CASIACD
CFBANKINFORMATION
CFHOMEPAGEAPI
CFHOMEPAGESIDECAR
CFLOANAPPLICATION
BROKERAGECHECKOUTORCHESTRATOR
CHECKOUTSIDECAR
CLOUDMONITORING
CLOUDRABBITHOLE
COMMONSAFFILIATEMANAGEMENT
COMMONSESIGN
COMMONSFIDOR
COMMONSFILESTORAGE
COMMONSPERSON
COMMONSSCENARIOORCHESTRATOR
COMMONSSCHUFA
COMMONSSCRIPTSYNC
COMMONSTASKSCHEDULER
DIGITALACCOUNTCHECK
BROKERAGEDOCUMENTFORWARDER
BROKERAGEDOCUMENTUPLOAD
GINISIDECAR
PRINT2MAIL
SMARKETENDPOINT
SMARKETFILTERENGINE
SMARKETMODIFIERENGINE
SMARKETORCHESTRATOR
SMARKETPUSH
SMARKETSCORINGENGINE
CFSIDECAR
COMMONSARVATOBIG
COMMONSBANKACCOUNTVALIDATOR
COMMONSSCORING
COMMONSSCRIPTRUNNER
COMMONSUSER
COMMONSAPIGATEWAY'

EUREKA_URL='http://213.183.195.222:8761/eureka/apps'
for app in $APPLICATIONS; do
  app_status_page_urls=$(curl -k -s ${EUREKA_URL}/${app} | grep statusPageUrl | awk -F '[<>]' '{print $3}' )
  for url in ${app_status_page_urls}; do
    echo "scriptexporter_analyser_http_status{app=\"$app\",url=\"$url\"} $(curl -s -o /dev/null -I -w "%{http_code}" $url)" &
  done
done
